baseURL = 'http://localhost:1313'
defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = false

title = 'TrataMentes - Massagem Terapêutica Lisboa e Cascais'
theme = 'tratamentes'

[params]
  description = 'Massagem terapêutica profissional em Lisboa e Cascais. Mais de 20 anos de experiência no alívio de dores crónicas, stress e problemas de sono.'
  phone = '+351 937 543 312'
  email = 'contato@tratamentes.pt'
  author = 'João Goulart'
  
  # Google Tag Manager
  gtm_id = 'GTM-XXXXXXX'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = 'Início'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Sobre'
  url = '/sobre/'
  weight = 2

[[menu.main]]
  name = 'Serviços'
  url = '/servicos/'
  weight = 3

[[menu.main]]
  name = 'Contacto'
  url = '/contacto/'
  weight = 4

